variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - CONTRIBUTING.md
      - README.md

stages:
  - stage: test
    displayName: Test
    jobs:
      - job: test
        displayName: Unit tests
        pool:
          vmImage: ${{ variables.vmImage }}
        steps:

          - task: NodeTool@0
            displayName: Use Node.js ${{ variables.nodejsVersion }} 
            inputs:
              versionSpec: ${{ variables.nodejsVersion }}
        
          - task: Npm@1
            displayName: Install dependencies
            inputs:
              command: custom
              customCommand: ci
        
          - task: Npm@1
            displayName: 'Lint'
            inputs:
              command: 'custom'
              customCommand: 'run ci:lint'

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            displayName: Publish lint results
            inputs:
              testRunner: JUnit
              testResultsFiles: '**/lint-results.xml'
              testRunTitle: ${{variables.name}}-lint-results

          - bash: | 
              export NOCK_BACK_MODE=lockdown
              npm run ci:test
            displayName: Run unit tests
        
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            displayName: Publish unit tests
            inputs:
              testRunner: JUnit
              testResultsFiles: '**/test-results.xml'
              testRunTitle: ${{variables.name}}-unit-tests

          - task: PublishCodeCoverageResults@1
            condition: succeededOrFailed()
            displayName: Publish code coverage report
            inputs: 
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'

  - stage: publish
    displayName: Publish
    jobs:
      - job: publish
        displayName: Publish artifacts
        pool:
          vmImage: ${{ variables.vmImage }}
        steps:
          - task: NodeTool@0
            displayName: Use Node.js ${{ variables.nodejsVersion }} 
            inputs:
              versionSpec: ${{ variables.nodejsVersion }}
          - task: Npm@1
            displayName: Install dependencies
            inputs:
              command: custom
              customCommand: ci
          - task: Npm@1
            displayName: Publish npm package
            inputs:
              command: publish
              publishRegistry: useFeed
              publishFeed: $(System.TeamProject)/${{variables.releaseFeedName}}
